# Generated by Django 4.2.7 on 2024-07-27 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonkTraderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='file',
            field=models.FileField(upload_to='static/education/'),
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=255)),
                ('bias', models.CharField(max_length=50)),
                ('entry', models.DecimalField(decimal_places=4, max_digits=10)),
                ('SL', models.DecimalField(decimal_places=4, max_digits=10)),
                ('TP', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
